-- Create Table CREDIT_CARD

DROP TABLE IF EXISTS CREDIT_CARD;
CREATE TABLE CREDIT_CARD (
    CLIENT_NUM INT,
    CARD_CATEGORY VARCHAR(20),
    ANNUAL_FEES INT,
    ACTIVATION_30_DAYS INT,
    CUSTOMER_ACQ_COST INT,
    WEEK_START_DATE DATE,
    WEEK_NUM VARCHAR(20),
    QTR VARCHAR(10),
    CURRENT_YEAR INT,
    CREDIT_LIMIT DECIMAL(10,2),
    TOTAL_REVOLVING_BAL INT,
    TOTAL_TRANS_AMT INT,
    TOTAL_TRANS_CT INT,
    AVG_UTILIZATION_RATIO DECIMAL(10,3),
    USE_CHIP VARCHAR(10),
    EXP_TYPE VARCHAR(50),
    INTEREST_EARNED DECIMAL(10,3),
    DELINQUENT_ACC VARCHAR(5)
);

-- CREATE TABLE CUSTOMER

DROP TABLE IF EXISTS CUSTOMER ;
CREATE TABLE CUSTOMER (
    CLIENT_NUM INT,
    CUSTOMER_AGE INT,
    GENDER VARCHAR(5),
    DEPENDENT_COUNT INT,
    EDUCATION_LEVEL VARCHAR(50),
    MARITAL_STATUS VARCHAR(20),
    STATE_CD VARCHAR(50),
    ZIPCODE VARCHAR(20),
    CAR_OWNER VARCHAR(5),
    HOUSE_OWNER VARCHAR(5),
    PERSONAL_LOAN VARCHAR(5),
    CONTACT VARCHAR(50),
    CUSTOMER_JOB VARCHAR(50),
    INCOME INT,
    CUST_SATISFACTION_SCORE INT
);

SELECT * FROM CREDIT_CARD;
SELECT * FROM CUSTOMER;

-- IMPORT CSV FILES

COPY CREDIT_CARD
FROM 'G:\Data Analysis\Power BI\Project\Project 2\Credit_Card_Financial_Dashboard-main\credit_card.CSV'
DELIMITER E'\t'
CSV HEADER

COPY CUSTOMER
FROM 'G:\Data Analysis\Power BI\Project\Project 2\Credit_Card_Financial_Dashboard-main\customer.CSV'
DELIMITER ','
CSV HEADER

COPY CREDIT_CARD
FROM 'G:\Data Analysis\Power BI\Project\Project 2\Credit_Card_Financial_Dashboard-main\cc_add.CSV'
DELIMITER E'\t'
CSV HEADER

COPY CUSTOMER
FROM 'G:\Data Analysis\Power BI\Project\Project 2\Credit_Card_Financial_Dashboard-main\cust_add.CSV'
DELIMITER ','
CSV HEADER


